# Generated by Django 5.2 on 2025-04-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
