# Generated by Django 5.2 on 2025-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_category_season_supplier_last_login_order_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
