# Generated by Django 5.2 on 2025-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
