# Generated by Django 5.2 on 2025-04-30 11:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_product_category_product_picture_product_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UniqueFileName('product_images/')),
        ),
    ]
