# Generated by Django 5.2 on 2026-07-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emailotp_remove_buyer_password_remove_buyer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='password',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='username',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('supplier', 'Supplier')], default='buyer', max_length=10),
        ),
    ]
