# Generated by Django 5.2 on 2026-07-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_product_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
